[package]
name = "yui-kr"
version = "0.1.0"
authors = ["Taketo Sano <taketo1024@gmail.com>"]
description = "YUI-KR"
license = "MIT"
edition = "2021"

[[bin]]
name = "ykr"
path = "src/bin/main.rs"

[lib]
path = "src/lib/lib.rs"

[features]
batch_test = []

[profile.release]
debug = true
overflow-checks = true

[dependencies]
yui  =         { git = "https://github.com/taketo1024/yui", branch = "develop" }
yui-link =     { git = "https://github.com/taketo1024/yui", branch = "develop" }
yui-matrix =   { git = "https://github.com/taketo1024/yui", branch = "develop" }
yui-homology = { git = "https://github.com/taketo1024/yui", branch = "develop" }
# yui  =         { path = "../yui/yui" }
# yui-link =     { path = "../yui/yui-link" }
# yui-matrix =   { path = "../yui/yui-matrix" }
# yui-homology = { path = "../yui/yui-homology" }

num-bigint = "0.4.4"
num-traits = "0.2.16"
itertools = "0.11.0"
petgraph = "0.6.4"
derive_more = "0.99.17"
cartesian = "0.2.1"
delegate = "0.10.0"
num-integer = "0.1.45"
rayon = "1.8.0"
log = "0.4.20"
simplelog = "0.12.1"
clap = { version = "4.4.8", features = ["derive", "cargo"] }
csv = "1.3.0"
serde = "1.0.192"
serde_json = "1.0.108"
ahash = "0.8.6"
