[package]
name = "yui-kr"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
overflow-checks = true

[dependencies]
yui  =         { git = "https://github.com/taketo1024/yui", branch = "develop" }
yui-link =     { git = "https://github.com/taketo1024/yui", branch = "develop" }
yui-matrix =   { git = "https://github.com/taketo1024/yui", branch = "develop" }
yui-homology = { git = "https://github.com/taketo1024/yui", branch = "develop" }
# yui  =         { path = "../yui/yui" }
# yui-link =     { path = "../yui/yui-link" }
# yui-matrix =   { path = "../yui/yui-matrix" }
# yui-homology = { path = "../yui/yui-homology" }

num-bigint = "0.4.4"
num-traits = "0.2.16"
itertools = "0.11.0"
petgraph = "0.6.4"
derive_more = "0.99.17"
cartesian = "0.2.1"
delegate = "0.10.0"
num-integer = "0.1.45"
rayon = "1.8.0"
tailcall = "0.1.6"
