[package]
name = "yui-kr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.4"
num-traits = "0.2.16"
itertools = "0.11.0"
petgraph = "0.6.4"
derive_more = "0.99.17"
cartesian = "0.2.1"

yui-core       = { git = "https://github.com/taketo1024/yui.git", branch = "develop" }
yui-ratio      = { git = "https://github.com/taketo1024/yui.git", branch = "develop" }
yui-polynomial = { git = "https://github.com/taketo1024/yui.git", branch = "develop" }
yui-lin-comb   = { git = "https://github.com/taketo1024/yui.git", branch = "develop" }
yui-utils      = { git = "https://github.com/taketo1024/yui.git", branch = "develop" }
yui-matrix     = { git = "https://github.com/taketo1024/yui.git", branch = "develop" }
yui-link       = { git = "https://github.com/taketo1024/yui.git", branch = "develop" }
yui-homology   = { git = "https://github.com/taketo1024/yui.git", branch = "develop" }
yui-khovanov   = { git = "https://github.com/taketo1024/yui.git", branch = "develop" }
delegate = "0.10.0"
num-integer = "0.1.45"
rayon = "1.8.0"
